### ISSUE TITLE
Upgrade heroku

### ISSUE THREAD

**Issue by delianides** [NewSpring/Hubot#4]
@jbaxleyiii @jonhorton  WIth heroku's new pricing structure and limited free plan, I think it makes sense to bump us to the minimum plan ($7).

Thoughts?

**Comment by jbaxleyiii** [comment]
@delianides I would like to look at moving it to AWS but in the interim that level seems sufficient to me

**Comment by jonhorton** [comment]
@delianides @jbaxleyiii Are we not grandfathered into our existing plan?

**Comment by jbaxleyiii** [comment]
@jonhorton from Heroku

"Existing applications with a single 1x dyno will be migrated to the new Free dyno after July 1, 2015. Once generally available, the new dyno types and pricing will be the default for new applications."

**Comment by delianides** [comment]
Hmmm, strange. Actually it isn't Apollos thats giving me the error reports, its the geckoboard app. All of our other apps are fine but for some reason that app was migrated to the new pricing structure.
